version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=input your user
      - POSTGRES_PASSWORD=input your pass
    ports:
      - 'port1:port2'
    volumes:
      - db:/var/lib/postgresql/data
      - 'your file path':'your docker data file path'
volumes:
  db:
    driver: local
